/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Clauidio
 */
public class FrmRegistroApoderado extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistroPadre
     */
    public FrmRegistroApoderado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtDni = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidopaterno = new javax.swing.JTextField();
        txtApellidomaterno = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelefonoA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreoE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtParentesco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnUsarA = new javax.swing.JButton();
        btnCancelarA = new javax.swing.JButton();
        btnEditarA = new javax.swing.JButton();
        btnRegistrarA = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtPago = new javax.swing.JCheckBox();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185), 2));
        jPanel3.setLayout(null);

        txtDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtDni);
        txtDni.setBounds(30, 40, 200, 24);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("DNI:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(30, 20, 40, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("NOMBRES:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 70, 80, 17);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombre);
        txtNombre.setBounds(30, 90, 200, 24);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("APELLIDO PATERNO:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 120, 130, 15);

        txtApellidopaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApellidopaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtApellidopaterno);
        txtApellidopaterno.setBounds(30, 140, 200, 24);

        txtApellidomaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApellidomaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtApellidomaterno);
        txtApellidomaterno.setBounds(30, 190, 200, 24);

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtTelefono);
        txtTelefono.setBounds(30, 240, 200, 24);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("TELÉFONO:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(30, 220, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("TELÉFONO ADICIONAL:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(260, 20, 150, 17);

        txtTelefonoA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefonoA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        txtTelefonoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoAActionPerformed(evt);
            }
        });
        jPanel3.add(txtTelefonoA);
        txtTelefonoA.setBounds(260, 40, 200, 24);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CORREO ELECTRÓNICO:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(260, 70, 160, 15);

        txtCorreoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCorreoE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtCorreoE);
        txtCorreoE.setBounds(260, 90, 200, 24);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("DIRECCIÓN:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(260, 120, 80, 15);

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtDireccion);
        txtDireccion.setBounds(260, 140, 200, 24);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("APELLIDO MATERNO:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 170, 130, 15);

        txtParentesco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtParentesco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtParentesco);
        txtParentesco.setBounds(260, 190, 200, 24);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("PARENTESCO:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(260, 170, 90, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("RESPONSABLE DE PAGO:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(260, 240, 160, 15);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(110, 170, 490, 300);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185), 2));
        jPanel2.setLayout(null);

        btnUsarA.setBackground(new java.awt.Color(174, 174, 174));
        btnUsarA.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnUsarA.setText("USAR DATOS");
        jPanel2.add(btnUsarA);
        btnUsarA.setBounds(70, 190, 170, 30);

        btnCancelarA.setBackground(new java.awt.Color(174, 174, 174));
        btnCancelarA.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCancelarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete_01_24x24-32.gif"))); // NOI18N
        btnCancelarA.setText("CANCELAR");
        jPanel2.add(btnCancelarA);
        btnCancelarA.setBounds(70, 150, 170, 30);

        btnEditarA.setBackground(new java.awt.Color(174, 174, 174));
        btnEditarA.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnEditarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        btnEditarA.setText("EDITAR");
        jPanel2.add(btnEditarA);
        btnEditarA.setBounds(70, 110, 170, 30);

        btnRegistrarA.setBackground(new java.awt.Color(79, 59, 185));
        btnRegistrarA.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRegistrarA.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarA.setText("REGISTRAR");
        jPanel2.add(btnRegistrarA);
        btnRegistrarA.setBounds(70, 70, 170, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(620, 170, 310, 300);

        jPanel4.setBackground(new java.awt.Color(79, 59, 185));
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DATOS DEL APODERADO");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(370, 10, 210, 20);

        txtPago.setBackground(new java.awt.Color(255, 255, 255));
        txtPago.setText("SI");
        jPanel4.add(txtPago);
        txtPago.setBounds(420, 410, 40, 25);

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("X");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel4.add(btnSalir);
        btnSalir.setBounds(900, 0, 60, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(40, 30, 960, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefonoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoAActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroApoderado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistroApoderado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarA;
    public javax.swing.JButton btnEditarA;
    public javax.swing.JButton btnRegistrarA;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnUsarA;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField txtApellidomaterno;
    public javax.swing.JTextField txtApellidopaterno;
    public javax.swing.JTextField txtCorreoE;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtDni;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JCheckBox txtPago;
    public javax.swing.JTextField txtParentesco;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtTelefonoA;
    // End of variables declaration//GEN-END:variables
}
