/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Clauidio
 */
public class FrmRegistroPadre extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistroPadre
     */
    public FrmRegistroPadre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtDni = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidopaterno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellidomaterno = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelefonoA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCorreoE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtApoderado = new javax.swing.JCheckBox();
        txtCodigo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPago = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnUsar = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cmdGrado1 = new javax.swing.JComboBox<>();
        txtVacante = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmdNivel = new javax.swing.JComboBox<>();
        cmdSeccion = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel1.add(txtBuscar);
        txtBuscar.setBounds(640, 120, 370, 30);

        btnbuscar.setBackground(new java.awt.Color(79, 59, 185));
        btnbuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        btnbuscar.setText("BUSCAR");
        jPanel1.add(btnbuscar);
        btnbuscar.setBounds(480, 120, 150, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185), 2));
        jPanel3.setLayout(null);

        txtDni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtDni);
        txtDni.setBounds(30, 40, 200, 24);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("DNI:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(30, 20, 40, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("NOMBRES:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 70, 80, 17);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombre);
        txtNombre.setBounds(30, 90, 200, 24);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("APELLIDO PATERNO:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 120, 130, 15);

        txtApellidopaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApellidopaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtApellidopaterno);
        txtApellidopaterno.setBounds(30, 140, 200, 24);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("APODERADO:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 240, 100, 15);

        txtApellidomaterno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApellidomaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtApellidomaterno);
        txtApellidomaterno.setBounds(30, 190, 200, 24);

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtTelefono);
        txtTelefono.setBounds(260, 40, 200, 24);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("TELÉFONO:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(260, 20, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("TELÉFONO ADICIONAL:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(260, 70, 150, 17);

        txtTelefonoA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefonoA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        txtTelefonoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoAActionPerformed(evt);
            }
        });
        jPanel3.add(txtTelefonoA);
        txtTelefonoA.setBounds(260, 90, 200, 24);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CORREO ELECTRÓNICO:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(260, 120, 160, 15);

        txtCorreoE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCorreoE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtCorreoE);
        txtCorreoE.setBounds(260, 140, 200, 24);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("DIRECCIÓN:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(260, 170, 80, 15);

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel3.add(txtDireccion);
        txtDireccion.setBounds(260, 190, 200, 24);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("APELLIDO MATERNO:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 170, 130, 15);

        txtApoderado.setBackground(new java.awt.Color(255, 255, 255));
        txtApoderado.setText("SI");
        jPanel3.add(txtApoderado);
        txtApoderado.setBounds(120, 230, 40, 23);
        jPanel3.add(txtCodigo);
        txtCodigo.setBounds(30, 250, 50, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("RESPONSABLE DE PAGO:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(260, 240, 160, 15);

        txtPago.setBackground(new java.awt.Color(255, 255, 255));
        txtPago.setText("SI");
        jPanel3.add(txtPago);
        txtPago.setBounds(420, 230, 40, 23);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(260, 170, 490, 300);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185), 2));
        jPanel2.setLayout(null);

        btnRegistrar.setBackground(new java.awt.Color(79, 59, 185));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        jPanel2.add(btnRegistrar);
        btnRegistrar.setBounds(20, 30, 210, 30);

        btnCancelar.setBackground(new java.awt.Color(174, 174, 174));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete_01_24x24-32.gif"))); // NOI18N
        btnCancelar.setText("CANCELAR");
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(20, 110, 210, 30);

        btnUsar.setBackground(new java.awt.Color(174, 174, 174));
        btnUsar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnUsar.setText("USAR DATOS");
        jPanel2.add(btnUsar);
        btnUsar.setBounds(20, 150, 210, 30);

        btnSiguiente.setBackground(new java.awt.Color(174, 174, 174));
        btnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSiguiente.setText("SIGUIENTE");
        jPanel2.add(btnSiguiente);
        btnSiguiente.setBounds(20, 240, 210, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(760, 170, 250, 300);

        jPanel4.setBackground(new java.awt.Color(79, 59, 185));
        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DATOS DEL PADRE");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(370, 10, 160, 20);

        btnSalir.setBackground(new java.awt.Color(204, 0, 51));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("X");
        jPanel4.add(btnSalir);
        btnSalir.setBounds(900, 0, 60, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(40, 30, 960, 40);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185), 2));
        jPanel5.setLayout(null);

        cmdGrado1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdGrado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        cmdGrado1.setBorder(null);
        jPanel5.add(cmdGrado1);
        cmdGrado1.setBounds(10, 110, 180, 24);

        txtVacante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVacante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 59, 185)));
        jPanel5.add(txtVacante);
        txtVacante.setBounds(10, 230, 180, 24);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("VACANTES:");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(10, 210, 70, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("GRADO:");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(10, 90, 50, 15);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("NIVEL:");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(10, 30, 50, 15);

        cmdNivel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "INICIAL", "PRIMARIA", "SECUNDARIA" }));
        cmdNivel.setBorder(null);
        jPanel5.add(cmdNivel);
        cmdNivel.setBounds(10, 50, 180, 24);

        cmdSeccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmdSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        cmdSeccion.setBorder(null);
        jPanel5.add(cmdSeccion);
        cmdSeccion.setBounds(10, 170, 180, 24);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("SECCIÓN:");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(10, 150, 70, 15);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(40, 170, 210, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTelefonoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistroPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistroPadre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSiguiente;
    public javax.swing.JButton btnUsar;
    public javax.swing.JButton btnbuscar;
    public javax.swing.JComboBox<String> cmdGrado1;
    public javax.swing.JComboBox<String> cmdNivel;
    public javax.swing.JComboBox<String> cmdSeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JTextField txtApellidomaterno;
    public javax.swing.JTextField txtApellidopaterno;
    public javax.swing.JCheckBox txtApoderado;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JLabel txtCodigo;
    public javax.swing.JTextField txtCorreoE;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtDni;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JCheckBox txtPago;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtTelefonoA;
    public javax.swing.JTextField txtVacante;
    // End of variables declaration//GEN-END:variables
}
